# Generated by Django 4.2.9 on 2024-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "model",
                    models.FileField(upload_to="models_train/", verbose_name="Modelo"),
                ),
                (
                    "graph_acuracia",
                    models.ImageField(
                        upload_to="images_accuracy/", verbose_name="Gráfico de acurácia"
                    ),
                ),
                (
                    "graph_predicao",
                    models.ImageField(
                        upload_to="images_pred/", verbose_name="Gráfico de predição"
                    ),
                ),
                (
                    "graph_confusion_matrix",
                    models.ImageField(
                        upload_to="graphs/",
                        verbose_name="Gráfico de matriz de confusão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Tool",
                "verbose_name_plural": "Training Tools",
            },
        ),
    ]
