# Generated by Django 4.2.9 on 2024-03-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training_tool", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingtool",
            name="graph_predicao",
        ),
    ]
