# Generated by Django 4.2.9 on 2024-03-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_tool", "0002_remove_trainingtool_graph_predicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtool",
            name="historico",
            field=models.ImageField(
                blank=True, null=True, upload_to="historico/", verbose_name="Histórico"
            ),
        ),
        migrations.AlterField(
            model_name="trainingtool",
            name="graph_acuracia",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images_accuracy/",
                verbose_name="Gráfico de acurácia",
            ),
        ),
        migrations.AlterField(
            model_name="trainingtool",
            name="graph_confusion_matrix",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="graphs_cm/",
                verbose_name="Gráfico de matriz de confusão",
            ),
        ),
    ]
